pipeline {
  agent { label 'Slave01' }

  options {
    skipDefaultCheckout()
  }

  stages {
    stage('Checkout source code') {
      steps {
        git branch: 'master',
            credentialsId: 'jenkins_github_pac',
            url: 'https://github.com/nhatpv1307/react-for-demo.git'
        sh "ls -la"
      }
    }

    stage ('Install dependencies') {
      tools {
        nodejs 'nodejs'
      }
      steps {
        sh '''
          echo "Installing..."
          npm install
          echo "Install dependencies successfully."
          ls -al
        '''
      }
    }

    stage ('Build') {
      steps {
        nodejs(nodeJSInstallationName: 'nodejs') {
          sh 'echo "Build application..."'
          sh 'npm run build'
          sh 'echo "Build application successfully."'
          sh 'ls -al'
        }
        script {
          stash includes: 'build/', name: 'build'
          stash includes: 'docker/', name: 'docker_folder'
        }
      }
    }
    
    stage ('Test') {
      tools {
        nodejs 'nodejs'
      }
      steps {
        sh 'echo "Run unit test..."'
        sh 'npm test'
        sh 'echo "Run unit test successfully."'
        sh 'ls -al'
      }
    }

    stage ('Create docker images') {
      agent any
      steps {
        script {
          unstash 'build'
          unstash 'docker_folder'
        }
        sh '''
          ls -al
          echo "Starting to build docker image"
          docker build -t pick-color:v1 -f docker/Dockerfile.no_build .
        '''
      }
    }
  }
}
